project:
  type: book

book:
  title: "Gregor Joseph Werner: A thematic catalogue of his works"
  author: Wolfgang Esser-Skala
  date: 2024-02-11
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib
# csl: "apa-6th-edition.csl"

format:
  html:
    theme:
      light: flatly
      dark: darkly
