project:
  type: book

book:
  title: "Gregor Joseph Werner: A thematic catalogue of his works"
  author: Wolfgang Esser-Skala
  date: 2024-02-25
  date-format: "YYYY-MM-DD [(v0.1.0)]"
  chapters:
    - index.qmd
    - guidelines.qmd
    - part: "Vocal music"
      chapters:
        - groups/oratorios.qmd
        - groups/masses.qmd
        - groups/requiems.qmd
        - groups/liturgical_works.qmd
        - groups/german_arias.qmd
        - groups/hymns.qmd
        - groups/litanies.qmd
        - groups/vespers.qmd
        - groups/marian_antiphons.qmd
        - groups/te_deums.qmd
        - groups/lamentations.qmd
        - groups/profane_cantatas.qmd
    - part: "Instrumental music"
      chapters:
        - groups/sonatas.qmd
        - groups/pastorellas.qmd
        - groups/partitas.qmd
        - groups/sinfonias.qmd
        - groups/concertos.qmd
    - part: "Appendix"
      chapters:
        - groups/spurious.qmd
  page-navigation: false

bibliography: references.bib
csl: "apa-6th-edition.csl"

format:
  html:
    toc-depth: 2
    theme:
      light: flatly
      dark: darkly
