project:
  type: book

book:
  title: "Gregor Joseph Werner: A thematic catalogue of his works"
  author: Wolfgang Esser-Skala
  date: 2024-02-11
  chapters:
    - index.qmd
    - part: "Vocal music"
      chapters:
        - works/oratorios.qmd
        - works/masses.qmd
        - works/requiems.qmd
        - works/liturgical_works.qmd
        - works/german_arias.qmd
        - works/hymns.qmd
        - works/litanies.qmd
        - works/vespers.qmd
        - works/marian_antiphons.qmd
        - works/te_deums.qmd
        - works/lamentations.qmd
        - works/profane_cantatas.qmd
    - part: "Instrumental music"
      chapters:
        - works/sonatas.qmd
        - works/pastorellas.qmd
        - works/partitas.qmd
        - works/sinfonias.qmd
        - works/concertos.qmd
    - part: "Appendix"
      chapters:
        - works/spurious.qmd

bibliography: references.bib
csl: "apa-6th-edition.csl"

format:
  html:
    theme:
      light: flatly
      dark: darkly
