project:
  type: book

book:
  title: Gregor Joseph Werner
  subtitle: A thematic catalogue of his works (WerW)
  author: Wolfgang Esser-Skala
  date: today
  date-format: "YYYY-MM-DD [(v0.12.9000)]"
  site-url: https://www.gregor-joseph-werner.at
  sidebar:
    title: Gregor Joseph Werner. A thematic catalogue of his works (WerW)
  chapters:
    - index.qmd
    - metadata.qmd
    - groups/overview.qmd
    - part: "Vocal music"
      chapters:
        - groups/a.qmd
        - groups/b.qmd
        - groups/c.qmd
        - groups/d.qmd
        - groups/e.qmd
        - groups/f.qmd
        - groups/g.qmd
        - groups/h.qmd
        - groups/i.qmd
        - groups/j.qmd
        - groups/k.qmd
        - groups/l.qmd
    - part: "Instrumental music"
      chapters:
        - groups/m.qmd
        - groups/n.qmd
        - groups/o.qmd
        - groups/p.qmd
        - groups/q.qmd
    - bibliography.qmd
    - part: "Appendix"
      chapters:
        - abbreviations.qmd
        - inventories.qmd
        - concordances.qmd
        - foreign_copies.qmd
        - guidelines.qmd
        - changelog.qmd
  page-navigation: false
  favicon: images/favicon.png

bibliography: references.bib
csl: "apa-6th-edition.csl"

format:
  html:
    toc-depth: 2
    theme:
      light: [flatly, styling.scss]
      dark: [darkly, styling.scss]
