project:
  type: book

book:
  title: Gregor Joseph Werner
  subtitle: A thematic catalogue of his works (WerW)
  author: Wolfgang Esser-Skala
  date: today
  date-format: "YYYY-MM-DD [(v0.11.0)]"
  site-url: https://www.gregor-joseph-werner.at
  sidebar:
    title: Gregor Joseph Werner. A thematic catalogue of his works (WerW)
  chapters:
    - index.qmd
    - metadata.qmd
    - groups/overview.qmd
    - part: "Vocal music"
      chapters:
        - groups/oratorios.qmd
        - groups/masses.qmd
        - groups/requiems.qmd
        - groups/liturgical_works.qmd
        - groups/german_works.qmd
        - groups/hymns.qmd
        - groups/litanies.qmd
        - groups/vespers.qmd
        - groups/marian_hymns.qmd
        - groups/te_deums.qmd
        - groups/lamentations.qmd
        - groups/profane_vocal.qmd
    - part: "Instrumental music"
      chapters:
        - groups/sonatas.qmd
        - groups/pastorellas.qmd
        - groups/partitas.qmd
        - groups/sinfonias.qmd
        - groups/concertos.qmd
    - bibliography.qmd
    - part: "Appendix"
      chapters:
        - abbreviations.qmd
        - inventories.qmd
        - concordances.qmd
        - foreign_copies.qmd
        - guidelines.qmd
        - changelog.qmd
  page-navigation: false
  favicon: images/favicon.png

bibliography: references.bib
csl: "apa-6th-edition.csl"

format:
  html:
    toc-depth: 2
    theme:
      light: [flatly, styling.scss]
      dark: [darkly, styling.scss]
