# Changelog {.unnumbered}

## 0.15.0 – 2025-06-29

### Added

- incipits and metadata for WerW B.8/67, D.2.8, D.4.3, D.5.1, E.3, F.33/34, G.4, H.1.1, H.2.10, I.1.3, I.2.3, I.3.2, I.4.2, I.5.2, N.1, O.6, and P.2
- sources: A-Wn F100.Moder.9, 14, 139, and 156–162
- work numbers in Reichert's catalogue of masses (reference Reichert 1935)
- instrument abbreviations *tr* and *vl princ*
- a link to the poster presented at the IAML 2025 Conference
- `util_make_events.R`: support for venue

### Changed

- updated metadata and incipits for WerW D.4.1/2/4, F.59, I.3.1, and N.2/15
- URL of development version now supports HTTPS

### Fixed

- table for Fonds Moder (previously, work links were messed up)



## 0.14.0 – 2025-05-25

### Added

- works: WerW G.L2 and H.1.L1
- incipits and metadata for WerW B.29, D.1.13, and O.5
- sources:
  - A-Wn: Fonds Moder 8, 13, 22, 33–35, 51–55, and 66
  - A-Z: lost textbooks (assigned to sources)
  - F-Pn: MS-2232 (WerW I.4.16)
  - H-Bn: lost textbooks (assigned to sources)
- references Harich1959 and editions Narkmun2024a–c, Paparozzi2021, and Warner1965a
- acknowledgements for H-Bn and Haydneum
- WerW M.24: shelfmark for source in A-SEI
- a siglum A-Wdtö for sources in the archive of the Denkmäler der Tonkunst in Österreich
- support for a list of hands (scribe, medium, type) in MEI metadata
- support for a list of performances (date, venue, place) in MEI metadata
- an appendix “Prints” that contains a table with all known modern editions
- links to the Klostermusiksammlungen database for A-GÖ and A-KN sources
- scripts:
  - `check_mei_consistency.R` for manually checking consistency across metadata files (list of hands, title, tempo)
  - `check_rism_entries.R` for comparing RISM entries in the catalogue to entries in the current RISM database
  - `util_make_events.R` for creating `<event>` elements from a list of performance dates/places (since it is cumbersome to enter long lists of performances in MerMEId)

### Changed

- WerW M.S1 has been renumbered to M.24; consequently, former WerW M.S2 is now M.S1.
- WerW D.2.L7 has been merged to D.1.13.
- Group I has been renamed (again) to “Marian antiphons”.
- Genres in metadata now adhere to the UNIMARC codes for musical forms. Notably, the terms “rorate” (now “introit”), “Marian antiphon/hymn” (now “antiphon”), “profane vocal music” (now “cantata”), and “te deum” (now “hymn”) have been removed.
- WerW G.S1: Metadata now contains all A-SEI performance dates.
- updated metadata for A-Wgm sources of WerW B.23, I.1.13, and M.24
- updated the favicon and title block banner background
- A warning is now issued for unknown RISM sigla.
- Fugues 1, 5, and 6 in H-Bn Ms. mus. IV. 2.166 have been assigned to their respective works.
- `get_mermaid_xml.sh` now
  - fixes `<ref>` elements, i.e., it removes the `label` and `target` attributes and, if missing, adds `targettype="pandoc-citation"`; and
  - adds a `type="ark"` attribute to `<altId>`.
- `error()` now has an argument `strict` which decides if the current R session should terminate.

### Fixed

- `svg_process_ly.sh` again creates correctly-sized SVG incipits (was broken by pdfcairo update in poppler 25.04).
- WerW G.8 is now correctly entitled “Litaniae de venerabili sacramento”.
- Source descriptions now contain no empty bullet points.
- The hand-written sources of WerW O.1–12 are now only assigned to their actual works.


## 0.13.0 – 2025-04-18

### Added

- manual incipits and metadata: WerW D.1.12, D.2.1, D.4.2, D.5.S3, E.2, F.4/41/S1, G.1, H.1.4, H.2.1, H.3.1, I.1.23, I.2.2, I.3.3/S1, I.4.9, I.5.16, J.6, N.15, O.3/4, P.10, and Q.S1
- sources:
  - A-KN: D-I-614a-03 and 29
  - A-Wst: A-14984
  - D-As: 4 Tonk 1513
  - H-Bn: Ms. mus. IV. 2.166
- references: Dlabac1815, Neuhuber2020, Perutkova2022, Schindler1969, Tank1981, and Winkler2010
- acknowledgements for A-Wst, CZ-Pak, H-Gk (updated), J-Tma, and Pernerstorfer
- Archival Resource Keys for each catalogue entry and MEI file, including the `?info` inflection that links to Dublin Kernel metadata
- citations of all known modern editions (`editions.bib`)
- a `.htaccess` file that redirects ARKs to the resolver <http://ark.esser-skala.at>
- a post-render script `post_render.sh` that copies metadata files to the output folder
- info on uncatalogued funds in CZ-Bm
- a check that the `targettype` attribute of the `<ref>` tag in a bibliography item has the correct value
- a function `summarise_loglevels()` that prints the total number of errors and warnings in the logfile

### Changed

- `get_mermeid_xml` now adds the ARK as `<altId>` tag and reads the catalogue of works prefix from `config.yml`. Thus, it now requires only a single argument.
- The log file is now saved in the folder `data_generated`.

### Fixed

- Publisher locations are now separate fields in the BibTeX file.


## 0.12.0 – 2025-03-08

### Added

- works: WerW B.S9, I.1.L1, and O.S1
- manual incipits and metadata: WerW B.46, D.2.11, F.31/59, G.3, H.1.7, H.2.9, I.1.8, I.3.6, I.4.4, I.5.19, M.23, and O.2
- sources:
  - A-KN: 73/3
  - A-KR: 48/9
  - A-Wgm: I 35469/1+2, I 73643, IX 73837, and VII 23528/1–3
  - A-WIL: 2304
  - A-Wn: F100.Moder.7, 12, 21, 31, 32, 46–50, 56–65, 75, 85/1, 99, and 100
  - A-Z: I/174, I/175, I/187, and IV/38
  - F-Pn: MS-2231
- references Czernin 2020b, Horvath 1971, Kim 1998, Maillard 1999, Neumayr 2018, Robbins Landon 1977, Sauer 1809, and Schreiner 2001
- acknowledgements for A-Gdab, A-KR, A-Wdp, RUS-Mrg, SK-BRm, US-NYp, Armstrong, Grosch, Größinger, Narkmun, Perutková, and Stadler
- a section describing works not yet catalogued 
- methods now mention the number of works in RISM that have been included
- WerW B.1: details on source H-Bn Mus.ms.III.14
- WerW B.35: details on source H-Gk AMC, Miss. 10.
- WerW B.65: shelfmark in CZ-Bm
- WerW L.1/2: shelfmarks in A-Wst and GB-Lbl
- WerW M.17-22/P.4-9: shelfmark in F-AG; infos on chronogram; dimensions of the print
- WerW M.S1: shelfmarks in RUS-Mrg and US-NYp; dimensions of the print
- WerW O.1–12: shelfmarks in A-KR and D-LI
- WerW P.3: information on 3rd movement
- appendix: more copies of foreign works
- info on Moder's Teilnachlass at the University of Salzburg
- Klosterneuburg inventory C

### Changed

- WerW numbers are now considered stable and citable.
- A source for WerW D.2.L8 has been discovered; thus, the work has been reclassified as WerW D.2.11.
- The following works have been renumbered: WerW B.24–28 → 72–76, 29 → S10, 30 → S11, 31–78 → 24–71; B.71 → 68, 74 → 69, L10 → 70, 68–70 → 71–73, 72/73 → 74/75, 75/76 → 76/77; D.4.5 → 7, 6 → 8, 7 → 5, 8 → 9, 9 → 6; D.5.2 → S3, 4 → S4, 5 → 4, 6 → 2; F.62 → S1, 63 → 62; and I.1.S1 → S2, 26 → S1, 27–31 → 26–30.
  
### Fixed

- incipits of WerW B.S7/S8 and I.1.S1
- shelfmarks A-Ed A 68 and A 69
- WerW B.1 and H.1.16: corrects classification of A-HE sources


## 0.11.0 – 2025-01-18

### Added

- works: WerW B.L10, D.3.S3, and D.5.L2
- manual incipits: WerW A.12, B.35, D.1.9, D.4.9, D.5.L2, E.28, and O.1
- metadata: WerW A.12, B.35, D.1.9, D.4.9, E.28, and O.1
- sources:
  - A-Wgm: Dopf's scores (I 59590–59639), I 35470, VI 37991/1+2, and VII 35473
  - A-Wn Mus.Hs.2120
  - D-B Mus.12727
  - H-VEs Hymnus 112/c (1–6)
- remaining entries in HarCa
- references Erdmann 2014 and Hochradner 2016
- a macro `\part` to the incipit header
- support for text incipits and roles in movements
- acknowledgements for A-SB, H-Gk, and H-VEs
- appendix:
  - concordances of previous catalogues to WerW
  - list of known copies of foreign works

### Changed

- WerW C.4 has been reclassified as C.S3. Thus, WerW C.S3 has been renumbered to C.S4.
- Main incipits are now numbered consecutively.

### Fixed

- incipit order for more than nine incipits


## 0.10.0 – 2024-12-14

### Added

- works: WerW D.4.9, I.5.27, P.10, and P.L8/L9
- manual incipits for WerW B.23/71, D.1.1/4, D.2.10, F.2/3/32, G.17, H.1.14/16, I.1.4, I.2.17, I.3.1/22, I.4.50, I.5.13, and M.18–22
- metadata for WerW B.23/71, D.1.1/4, D.2.10, D.5.4/5/7/S1, F.2/3/8/15/16/18–20/32/42/60/61, G.2/6/10/17, H.1.8/9/11/14/16, I.1.1/2/4/13/27/30/31, I.2.4/6/8/12/15–17, I.3.1/7/10/15/21/22, I.4.7/15–17/35/41/45/46/50/S1, I.5.5/7/10/13/23, J.2/3, M.17–22/S1, O.13, and Q.2–4
- sources:
  - WerW I.3.21: H-K Ms.748/a
  - WerW B.71: A-HE VIII a 6 and D-OB MO 312
  - Fonds Moder: 6, 11, 20, 29/1-7, 30, 37-45
  - copies in A-KN
- the identifier *HarCa*, which is Hárich's unfinished catalogue of works in A-Wgm (currently only for masses)
- support for prints and lost sources in metadata
- support for a repository name instead of a RISM siglum in the source location
- references: Armstrong 2004, Bardos 1976, 1980, 1984, Chase 2003, Esterházy inventories 1805 and 1812/13, Hansell 1968, Harman 1968, Herzogenburg inventories A and B, Klosterneuburg inventory B, Müller 1911, Narkmun 2024, Preisl 2022, Prominczel 2013, Radant 1982, Rheinfurth 1977, Rostetter 2023, and Weinmann 1978
- a detailed description of previous efforts to create a thematic catalogue
- metadata validation:
  - consistency between CSV and MEI (work title, references, identifiers, sources)
  - link label of source location, genre, and classification terms are from a vocabulary defined in `data/config.yml`
  - number of bars in sections sum up to number of bars in movement
  - scoring of sections (movement) sums up to scoring of movement (work)
  - instrument abbreviation corresponds to UNIMARC term
  - source title matches presentation and authority term
  - all movements are numbered and sections are not
  - there are no incipits in sections
- a link to the modern EES edition of a work (if available)
- an appendix *Inventories*, which contains tables describing Hárich's catalogue and the Fonds Moder
- acknowledgements for A-H, A-KN, A-MB, A-Wgm, A-Z, D-OB, H-K, and Hilscher
- the macro `\hA` to the incipit header
- shelfmark subnumbers to hymn collections in A-KN, H-Gk, and H-VEs
- `catalogue.log`, which contains the log file
- `data/instrument_abbreviations.csv`, which describes UNIMARC instrument abbreviations
- `data/library_sigla.csv`, which describes RISM library sigla
- `data/fonds_moder.csv`, which contains an inventory for the Fonds Moder

### Changed

- Sources are now formatted as table with one row for each source type (autograph, manuscript ...).
- Meters are now printed as SVGs from LilyPond's Emmentaler font.
- Source components are now rendered as itemized list.
- WerW H.2.12 has been merged to H.1.16 (5th movement).
- WerW I.2.23 has been merged to I.2.22. Thus, WerW I.2.24 has been renumbered to I.2.23.
- WerW I.3.L1 has been reclassified as I.3.S1, with source A-Ee N0226.
- WerW D.3.2 has been reclassified as D.3.S2. Thus, WerW D.3.3–8 have been renumbered to D.3.2–7.
- WerW D.5.3 has been reclassified as D.5.S2. Thus, WerW D.5.4–7 have been renumbered to D.5.3–6.
- The XML processing script (renamed to `get_mermeid_xml.sh`) now downloads files from the eXist-db database and validates them against the mei-CMN schema.


### Fixed

- References in metadata are (again) encoded with a `<ref>` element to conform with the MEI schema.
- description of HarIn in guidelines (prefixes were swapped)


## 0.9.0 – 2024-10-12

### Added

- works: WerW B.78/S7, G.S2, and P.L4–7
- manual incipits for WerW B.54, D.2.7, G.S1, H.2.11/12, and N.2
- metadata for WerW B.54, D.3.1/3–7/S1, D.2.7, G.S1, H.2.11/12, and N.2
- all missing short incipits (except for oratorios)
- sources:
  - fonds Moder: 3–5 and 10 (checked); 19, 25, 28, 29/2, 49, 54, 85/5, 102, 158/6, 160, and 120 (from @WinklerKlement2013; still need to be verified)
  - A-SEI: E VIII 3 e and f, FXXI 6 a and b, F XXII 7 a and b
- references: Baker 2013, Bogati 1936, Brtnice Inventory, Czernin 2018, Farkas 1994, Jones 1996, Lindner 2010, Moder 1985, Pausch 1975, Rempe 1991, Rovatkay 2005, Schlader 2019, Somfai 1963, Stein 1957, Strakova 1963, 1965, Walter 1976, and Warner 1965
- acknowledgements for A-Sd, A-SEI, A-WIL, A-Wps, and H-P
- support for (modern) editions in the bibliography of work details
- a check for running catalogue of work numbers
- export of a table that lists all works (`data_generated/work_list.xlsx`)

### Changed

- XML syntax for references in MEI metadata now accomodates both normal references and modern editions.
- WerW numbers and RISM IDs in metadata text are now formatted as hyperlinks.
- WerW M.24 has been renumbered to M.23.
- Group H (“Vespers”) has been renamed to “Vespers and psalms”.
- WerW D.4.7 has been split into D.4.7. and D.4.8.
- WerW G.22 has been reclassified as spurious work and thus has been renumbered to G.S3.
- WerW I.1.30 has been reclassified as spurious work and thus has been renumbered to I.1.S1. Accordingly, I.1.31/32 have been renumbered to I.1.30/31.
- WerW I.5.11 and 13 have been merged. Consequently, I.5.14-27 have been renumbered to I.5.13-26.
- Guidelines now also specify where to put performance dates.
- In the work details, the work description is now printed below the bibliography.

### Fixed

- If the bibliography in work metadata is empty, it is now completely omitted from the printed work details. (Previously, a dash was printed.)


## 0.8.0 – 2024-09-08

### Added

- manual incipits for WerW B.1/7/33/38/40/42/47/51/52/58/S6, B.48 (Agnus Dei), D.1.8, D.3.7, E.34, J.S1, K.3, and P.3 
- metadata for WerW B.1/7/33/38/40/42/47/48/51/52/58/70/S6, C.S3, D.1.5–8/10/11, D.2.5/6, D.3.7, E.1/34/38/S1, J.S1, K.3, and P.3
- new sources for WerW I.3.3 (A-Wn F100.Moder.1/2), I.3.21 (A-Wn F100.Moder.2), I.5.20 (A-Wn F100.Moder.1/1), and P.S1 (St Peter inventory)
- a macro `\hy` to the LY incipit header, which prints a hyphen in lyrics
- a macro `\skips` to the LY incipit header, which skips notes for lyrics
- Identifiers in works details are now links to the respective reference.
- The following metadata fields are now also supported and thus included in the work details: several work titles, genre, general notes on the work level, number of voices in vocal ensemble, roles, and notes for movements.
- acknowledgements for A-GÖ
- information on currently undiscoverable A-HE sources (WerW G.11/14, I.4.2/53, and J.3)

### Changed

- The XML preparation script now converts and renames all XML files in the folder. It requires a first argument which corresponds to the catalogue of works abbreviation. Thus, `WerW_B_1.xml` is processed and renamed to `B_1.xml`.
- Parameters for R scripts are now in a YAML file (`script/config.yml`). Thereby, only this file has to be changed if the code base is reused for different projects.
- Group C has been renamed (Requiems, Libera -> Requiems). Accordingly, WerW C.5 has been renumbered to D.3.6, which has shifted former D.3.6/7 to D.3.7/8.
- WerW B.75 has been reclassified as spurious work and thus has been renumbered to B.S6. Accordingly, WerW B.76–78 have been renumbered to WerW B.75–77.
- WerW D.1.5 has been reclassified as offertory and thus has been renumbered to D.2.6. Accordingly, the following works have been renumbered: WerW D.1.6–17 to 5–16, and D.2.6–9 to 7–10.
- WerW D.1.8 has been renamed and thus could be merged with D.2.L7. Accordingly, WerW D.2.L8/9 have been renumbered to D.2.L7/8.
- WerW J.6 has been reclassified as spurious work and thus has been renumbered to J.S1. Accordingly, WerW J.7 has been renumbered to WerW J.6.

### Fixed

- identifiers in metadata of WerW B.46 and Q.2
- Ensembles are now correctly sorted (soli always before coro). Moreover, the soli ensemble is renamed to solo if only a single voice participates in a movement.


## 0.7.0 – 2024-07-30

### Added

- manual incipits for WerW B.48, F.19/20/43, I.1.1, I.2.4, I.4.35, and Q.4.
- additional MEI metadata: dating, bibliography, and notes
- references: Kiesewetter 1847, Mayer 2020, Meyer 2020, Mitterschiffthaler 1997, Paczkowski 2019, Pernerstorfer 2020, Petermayr 2015, Petermayr 2022, Pohl 1875, Rovátkay 2020, Schlader 2020, Schubert 2007, Sherman 2001, Štefan 1985, Zelenka 1739, and Petermayr's draft catalogue of works 
- The catalogue now also comprises spurious and lost works (with incipits where known).
- The catalogue now comprises four reference columns: HarIn (Hárich 1975), PetWe (Petermayr 2015), PetSi (Petermayr 2020), and WinMa (Winkler-Klement 2020). These are linked to the bibliography.
- The overview table now includes the number of total, ascertained, lost, and spurious works in each group.
- A new chapter now describes the scope of work metadata. This chapter complements the more technical guidelines, which have thus been moved to the appendix.

### Changed

- Partitas from the Instrumental-Calender now have separate entries WerW O.1 to O.12.
- Accordingly, WerW O.2 was renumbered to O.13.
- Incipits are now always displayed in SVG format (white background with rounded corners), which greatly improves their appearance on high-resolution displays.
- If MEI metadata is available for a work, all data displayed on the group page are taken from this file.
- Incipits are now specified without file extension in MEI files.
- Work details are now wider to accommodate wide tables.
- The following groups were renamed: E (German church arias -> German sacred music), I (Marian antiphons -> Marian hymns), and L (Profane cantatas -> Profane vocal music).
- The bibliography now appears on a separate page.

### Fixed

- Parsing of dimensions in MEI metadata is now more robust.

### Removed

- `data/incipits A-KN.odt` and
- `scripts/make_rism_tables.R` (both files are now obsolete)


## 0.6.0 – 2024-07-13

### Added

- acknowledgements
- conversion of MEI metadata to markdown, so that work details are now included on the group page in a collapsed callout block

### Changed

- guidelines
- incipits for WerW B.46 are now in LY format

### Fixed

- generation of only necessary RISM incipits (previously, all RISM incipits were rendered since they were still named “main”)

### Removed

- HTML files exported from MerMEId
- `prepare_mermeid_html.sh`, since that script became obsolete


## 0.5.0 – 2024-06-30

### Added

- manual incipits for WerW B.70, D.1.11, D.5.5, G.6, I.4.41, J.12, M.17–22, P.4–9, Q.3, Z.9
- export of a table with works grouped per library


### Changed

- For works with several movements, the group page now displays one incipit per movement.


## 0.4.0 – 2024-06-16

### Added

- manual incipits for WerW C.5, D.3.4, D.5.4/7, E.1/38, F.15/16/18/60/61, G.2/10, H.1.8/9/11, I.1.2/13/27/31/32, I.2.6/8/12/15/16, I.3.7/10/15/21, I.4.15-17/45/46, I.5.5/7/10/24, J.3, N.2, O.2, and Z.5/6/15–17
- group H.3 (magnificats)
- work D.3.6
- sitemap, which is indexed by Google
- reference Harich 1932
- changelog as webpage

### Changed

- rendering of incipits, so that all of them have the same size
- clicking on an incipit opens the full-score incipit as lightbox
- work numbers
  - D.3.6 -> D.3.7
  - E.38 -> Z.17
  - E.39–41 -> E.38–40
- appearance of the index, with title block banner
- works list CSV now contains full RISM IDs for distinguishing works with same shelfmark
- technical workflow:
  1. assemble catalogue
  2. create RISM PAE incipits
  3. use GNU Make for engraving all incipits
  4. prepare pages
  
### Fixed

- work titles, notably of oratorios

### Removed

- column 'key' in works list CSV


## 0.3.0 – 2024-05-12

### Added

- support for LilyPond incipits
- details for WerW D.1.2 to D.1.4 and Q.2
- bash scripts for MerMEId HTML and XML post-processing
- favicon

### Changed

- format of group page (now only contains incipit and sources)
- format of work details page (lightbox support for incipit images)
- work numbers: D.2.9 -> Z.16, D.2.10 -> D.2.9
- updated guidelines

### Removed

- column 'ID' in works list CSV


## 0.2.0 – 2024-03-17

### Added

- guidelines for compiling metadata
- catalogue abbreviation “WerW”
- page with overview table
- sources Riedel 1979 and Harich 1975
- links to work detail pages
- manual incipits for WerW B.46, D.2.9, G.22, O.2, Q.2, Q.3, and Q.4
- MEI metadata for WerW B.46

### Changed

- group page and incipit generation
- catalogue is now provided in CSV format


## 0.1.0 – 2024-02-25

### Added

- initial release
