---
title-block-banner: true
---

# Introduction {.unnumbered}

This website contains an evolving thematic catalogue of Gregor Joseph Werner's works.

::: {.callout-important}
## Caution

This catalogue is **work-in-progress** and likely contains errors or duplicate entries. Its contents are subject to change as we screen more and more manuscripts.
:::

For general and biographical information on Werner, see @Bogati1936, @Czernin2020, @Moder1959, @Moder1985, @Petermayr2007, and @Unverricht2001.


## Overview

We classify Werner's works as *Vocal music* (groups A to L) and *instrumental music* (groups M to Q). Groups D, H, and I are further divided into subgroups to provide a more fine-grained classification and to preserve work numbering if further works are discovered. Within each (sub-)group, works are ordered by library and siglum; the more important libraries (H-Bn and A-Ed) appear first, followed by other libraries. Following works with ascertained authorship, lost works (prefix L followed by consecutive number) and spurious and uncertain attributions (prefix S followed by consecutive number) are included.


**Vocal music** comprises

- *A. Oratorios*
- *B. Masses*
- *C. Requiems*
- *D. Short liturgical works*<br/>
  (1) Motets<br/>
  (2) Offertories<br/>
  (3) Responsories<br/>
  (4) Rorates<br/>
  (5) Miscellaneous works
- *E. German sacred music*
- *F. Hymns*
- *G. Litanies*
- *H. Vespers and psalms*<br/>
  (1) Complete vespers<br/>
  (2) Psalms<br/>
  (3) Magnificats
- *I. Marian hymns*<br/>
  (1) Alma redemptoris mater<br/>
  (2) Ave Regina coelorum<br/>
  (3) Regina coeli<br/>
  (4) Salve Regina<br/>
  (5) Sub tuum praesidium
- *J. Te Deums*
- *K. Lamentations*
- *L. Profane vocal music*

**Instrumental music** comprises

- *M. Sonatas*
- *N. Pastorellas*
- *O. Partitas*
- *P. Sinfonias*
- *Q. Concertos*

The catalogue contains at least the following information for each work:

- title
- one or more incipits
- identifiers in other catalogues
- sources (linked to the respective RISM entry, if available)
- miscellaneous notes
- relevant literature

In addition, we are annotating more and more works with [detailed metadata](metadata.qmd) in MEI format [@MEI2023].

Works in the catalogue should be cited by the abbreviation “WerW”, followed by the group, subgroup (if applicable), and work number; the latter three components should be separated by a period.


## Methods

### Sources

We consulted the following sources, of which some contain partial catalogues of Werner's works:

- @Czernin2020a – sources in Austria
- @Dolezal2018 – database with digitized manuscripts of the Dommusikarchiv Eisenstadt
- @Dopf1956 – masses
- @Eitner1904 – sources known around 1900
- @Harich1932 – works in the National Szechenyi Library Budapest
- @Harich1975 – instrumental works
- @Harich1976 – oratorios
- @Mikusi2020 – sonatas
- @Muranyi1997 – works in the National Szechenyi Library Budapest
- @Petermayr2015 – German church arias and pastorellas
- @Petermayr2020 – instrumental works
- @WinklerKlement2013 – works in the Dommusikarchiv Eisenstadt
- @WinklerKlement2020 – masses and oratorios
- a draft catalogue of works by Klaus Petermayr (personal communication)


### Analysis

The work list assembled from these sources (`data/catalogue_works.csv`) was checked against and supplemented by RISM entries. To this end, entries were downloaded via [*sru-downloader*](https://github.com/rism-international/sru-downloader) on 2024-01-27, yielding 867 entries. In the resulting XML file, all tags in the `zs` namespace were removed, yielding the XML file `data/rism_entries.xml`, which only contains [MarcXML](https://www.loc.gov/standards/marcxml/) tags:

```bash
java -jar SRUDownloader.jar "https://muscat.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=creator=%22Werner,%20Gregor%20Joseph%22&maximumRecords=100"
grep -v "<zs:" output.xml | \
  grep -v "</zs:" | \
  grep -v "<marc:collection" | \
  grep -v "</marc:collection" | \
  sed '1 a\<marc:collection xmlns:marc="http://www.loc.gov/MARC21/slim">' | \
  sed '$ a\</marc:collection>' \
  > rism_entries.xml
rm output.xml
```

Pages for all groups of works were generated automatically from `catalogue_overview.csv` and `catalogue_works.csv`. If manually curated incipits were unavailable for a work, the first incipit of the first source with a RISM entry was included. Data from the [RISM Catalogue](https://opac.rism.info) (e.g., Plaine & Easie Code for incipits) by the *Répertoire International des Sources Musicales* is licensed under a Creative Commons Attribution CC-BY 3.0 Unported License.

Detailed work metadata was edited with [MerMEId v2.0](https://mermeid.edirom.de/). Incipits were either prepared with [MuseScore](https://musescore.org), polished with [mei-friend](https://mei-friend.mdw.ac.at), and rendered with [Verovio](https://www.verovio.org), or created with [LilyPond](https://lilypond.org/) and [EES Tools](https://github.com/edition-esser-skala/ees-tools). XML files were exported from MerMEId and post-processed. These pages are rendered using the [BravuraText](https://github.com/steinbergmedia/bravura) font v1.392 and Verovio.


### Data and code availability

Datasets and code used for preparing this catalogue are available from [GitHub](https://github.com/edition-esser-skala/werner-catalogue-of-works).


## Acknowledgements

Assistance of the following people and institutions is gratefully acknowledged:
Thomas Dolezal (Dommusikarchiv Eisenstadt – A-Ed),
Ute-Eva Thiem (Benediktinerabtei Stift Göttweig, Musikarchiv – A-GÖ),
P. Roman Nägele (Stift Heiligenkreuz im Wienerwald, Musikarchiv – A-HE),
Peter Deinhammer (Benediktinerstift Lambach, Musikarchiv – A-LA),
P. Michael Eppenschwandtner (Benediktinerabtei Michaelbeuern, Musikarchiv – A-MB),
Eva Neumayr (Archiv der Erzdiözese Salzburg, Musiksammlung – A-Sd),
P. Florian Ehebruster (Benediktinerstift Seitenstetten, Musikarchiv – A-SEI),
Ikarus Kaiser (Stift Wilhering, Musikarchiv – A-WIL),
Michael Sipka (Erzbischöfliches Priesterseminar – A-Wps),
Ilse Beel (Koninklijk Conservatorium Brussel, Bibliotheek – B-Bc),
Maria Šťastná (Knihovna Národního muzea, Praha – CZ-Pn and CZ-Pnm),
Gertraud Gaukesbrink (Santini-Bibliothek, Münster – D-MÜs),
Zita Grócz (Érseki Könyvtár, Kalocsa – H-K),
Damásdi Zoltán (Pécsi Egyházmegye, Pécsi Püspöki Levéltár, Székesegyházi Kottatár – H-P),
Klaus Petermayr (Oberösterreichisches Landesmuseum, Musiksammlung),
as well as the staff of
the Österreichische Nationalbibliothek, Musiksammlung, Wien (A-Wn),
the Staatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung (D-B),
the Sächsische Landesbibliothek - Staats- und Universitätsbibliothek, Dresden (D-Dl),
the Universitäts- und Landesbibliothek Darmstadt, Musikabteilung (D-DS),
the Duke University Libraries, Music Library, Durham, NC (US-DMu),
and the Zentral- und Hochschulbibliothek Luzern (CH-Lz).


## Contact

Would like to team up or support the project? Feel free to reach out to me via [email](mailto:wolfgang@esser-skala.at)!

Disclosure (§25 Mediengesetz)
: This website is privately provided and maintained by Wolfgang Esser-Skala, Wolfgangseestraße 31g, 5023 Koppl.
