# Metadata scope {.unnumbered}

Each individual work is documented as follows in MEI metadata. (For a technical documentation on how to enter these metadata in MerMEId, see [guidelines](guidelines.qmd).)


## General metadata

- **title** (one main, possibly fictitious, title; additional titles for works with several named movements such as responsories and vespers, and for the long title of oratorios)
- **incipits** (numbered consecutively)
- **identification**
  - *WerW*: number according to this catalogue
  - *Dopf*: thematic catalogue of masses by @Dopf1956
  - *HarCa*: thematic catalogue (unfinished) by @Harich1990
  - *HarIn*: Werner's inventory of 1737/38 (H-Bn Acta mus. 4251; p. 31–66; prefixes I–XIII, p. 31–66) and thematic catalogue of 1740 (prefixes A–G, p. 22–31) as described by @Harich1975
  - *PetSi*: catalogue of instrumental works by @Petermayr2020 (Kon: Konzerte, p. 462; Par: Partiten, p. 460f; Pas: Pastorellen (geistlich), p. 459f; Sin: Sinfonien, p. 461; Sog: Sonaten (geistlich), p. 458f; Sow: Sonaten (weltlich), p. 460)
  - *PetWe*: catalogue of Christmas music by @Petermayr2015 (P: Pastorellas, p. 190f; V: vocal music, p. 179–181)
  - *ReiMa*: number in the thematic catalogue of masses by @Reichert1935 (p. 141–143)
  - *WinMa*: catalogue of masses by @WinklerKlement2020
- **ARK**: Archival Resource Keys of the human-readable catalogue entry and the metadata in MEI format
- **scoring** ([abbreviations](https://opac.rism.info/scoring-abbreviations) as used in RISM)
- **roles** (optional; names of the vocal soloists)
- **genre** ([musical form](http://www.urfm.braidense.it/risorse/searchforms_en.php) as used in UNIMARC field 128)
- **place** and **date of composition**
- **performances**: location, venue (if known), number of performances, and dates
- **bibliography**
- **editions**
- **work notes** (e.g., why is an attribution spurious?)


## Music

This section describes the individual movements of the work.

- one entry for each **movement**
  - consecutive *number* (fictitious)
  - *title* (one or several)
  - *tempo*
  - *key*
  - *meter*
  - *extent* in bars
  - *scoring*
  - *roles* (optional)
  - *text incipit* (optional)
  - *notes* (optional)
  - orchestral *incipit*, comprising all instruments and voices
  - if applicable, a table describing individual **sections** (i.e., parts of the movement with distinct key, meter, scoring …)


## Sources

This section describes the known sources of the work.

- **source type** (autograph manuscript, partly autograph manuscript, manuscript copy, print, or lost manuscript)
- **classification** in six categories:
  - *content*: main type of content; ‘notated music’ or ‘text’ (e.g., libretti)
  - *presentation*: the source's basic mode of production or carrier; ‘manuscript’ or ‘print’
  - *authority*: ‘autograph’, ‘doubtful autograph’, ‘partly autograph’, or ‘copy’
  - *scoring*: ‘score’, ‘parts’, ‘vocal score’, or ‘score and parts’
  - *state*: the source's place in the process of creation or production ‘draft’, ‘fair copy’, or ‘first edition’
  - *completeness*:
    - ‘complete’ indicates that this source is complete
    - ‘incomplete’ indicates that one or more parts are missing from a set of parts
    - ‘excerpt’ designates a section of a work, published or copied for stand-alone performance
    - ‘fragment’ indicates that portions of the music are missing, e.g. a fragmentary sketch or a source from which pages are lost
- **location(s)** (library siglum, shelfmark, link to digitized version and/or catalogue entry)
- **RISM identifier**
- **publication** (publisher, place) and **dating**
- one or more **title pages** (each title page is labeled by its position and represents a diplomatic transcription)
- **physical description**
  - *extent* (number of parts or pages/folios)
  - approximate *size* in cm (height x width)
  - list of *hands* (full name, writing medium, type of contents)
  - number of *staves* per page, rastral size (if known)
- **components and notes**
  - individual *parts* with number of written pages in parentheses
  - miscellaneous *notes*
