#!/bin/bash

# location of the MEI schema for validation
MEI_SCHEMA=../../data_generated/mei-CMN.rng

# check for required arguments:
# (1) catalogue of works abbreviation
# (2) work number

if [ $# -ne 1 ]; then
  echo "Usage: get_mermeid_xml WORK"
  exit 1
fi

p=`yq .catalogue_prefix ../../data/config.yml`
s="${p}_$1.xml"
t="$1.xml"

# download the XML file from MerMEId via the WebDAV interface
# curl exits with code 18, but this is due to a limitation of eXist-db
echo "Downloading $s ..."
curl -s -o $s http://admin@localhost:8080/webdav/db/apps/mermeid-data/$s
curl_exit_code=$?
if [ $curl_exit_code -ne 0 ] && [ $curl_exit_code -ne 18 ]; then
  echo "Error while downloading"
  exit 1
fi

# check that the downloaded file existed in the database
if grep -q "Not Found (404)" $s; then
  echo "Error: File $s not found"
  rm $s
  exit 1
fi

echo "Processing ..."

# add an 'altId' element with the ARK
ark_prefix=`yq .ark ../../data/config.yml`
ark_suffix=`echo $1 | sed "s/_//g" | sed -E "s/(.*)/\L\1/g"`
ark="ark:$ark_prefix$ark_suffix"
xmlstarlet edit --inplace --insert '//_:fileDesc' -t elem -n altId -v $ark $s

# remove several XML elements
# revision description is automatically generated by MerMEId (currently useless)
xmlstarlet edit --inplace --delete '//_:revisionDesc' $s

# empty elements prevent validation
xmlstarlet edit --inplace --delete '//_:projectDesc' $s
xmlstarlet edit --inplace --delete '//_:classDecls' $s
xmlstarlet edit --inplace --delete '//_:langUsage' $s

# empty attribute 'quantity' prevents validation
xmlstarlet edit --inplace --delete '//_:extent/@quantity' $s
xmlstarlet edit --inplace --delete '//_:height[@quantity=""]' $s
xmlstarlet edit --inplace --delete '//_:width[@quantity=""]' $s
xmlstarlet edit --inplace --delete '//_:depth[@quantity=""]' $s
xmlstarlet edit --inplace --delete '//_:dim[@quantity=""]' $s

# empty nodes prevent validation
xmlstarlet edit --inplace --delete '//_:dimensions[@type="format"]' $s
xmlstarlet edit --inplace --delete '//_:dimensions[@type="rastral_mirror"]' $s

# currently unnecessary, make files large and less readable
xmlstarlet edit --inplace --delete '//@xml:id' $s

# validate the created XML file
echo "Validating ..."
xmllint --noout --pedantic --relaxng $MEI_SCHEMA $s

if [ $? -eq 0 ]; then
  mv $s $t
  echo "Successfully created $t"
else
  exit 1
fi
